name: money_tracker
description: "A money tracker app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  skeletonizer: ^1.4.2
  flutter_localizations:
    sdk: flutter
  intl: any
  shared_preferences: ^2.3.3
  provider: ^6.1.2
  uuid: ^4.5.1
  material_color_utilities: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
